### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by robertnicjoo** [Laralabs/toaster#2]
Hi,
Is there any demo or at least images to see what will be the results, and why we should use this package?

**Comment by clnt** [comment]
Hi,

There is no live demo or pictures because what you do with the data is essentially up to you. 

At the bottom of the documentation you will find a short guide on using this package with a Vue toast component, which is what inspired me to create this package. I could probably host a copy of the result of this short tutorial if needed.

The purpose of this package is to provide an easy way to create session messages within your controllers, and have them bound to your view in a JavaScript variable so that you can access them with Vue, Angular or React etc.
