### ISSUE TITLE
Suggestions to improve value proposition

### ISSUE THREAD

**Issue by shalvah** [Laralabs/toaster#3]
This is a nice library. I'd suggest you add a couple of images of how the toast notifications it generates look like, as people wouldn't like to commit to something they aren't sure of.

Also, in terms of syntax, I'm curious as to why `closeBtn` defaults to `false` **and** `expires` time is `null`. Wouldn't it make sense to have a limit like 30s for instance, as well as a close button available by default?

**Comment by dels07** [comment]
+1 , add some screenshot

**Comment by clnt** [comment]
Thanks for the input guys.

The reason there isn't a screenshot is because this package does not come with any form of style, it simply provides the JSON data to the view in a JS variable. 

It is then up to the user what they do with that data, at the bottom of documentation I included a section on using this with the [vue-toast](https://github.com/AStaroverov/vue-toast) component (which includes an example of what it looks like) - I will update this section of documentation with a preview screenshot though.

However, I would like to include a supported Vue, Angular and React component in a future release which is something I will be working on. Setting this up with the component above requires a fair few extra functions added to the Vue instance which is not ideal and something I want to improve.

Regarding the default properties, `closeBtn` defaults to `false` because usually these notifications are not needed with a close button and are set to auto expire, if the user wishes for a close button they can use the included `important()` helper function to set that flag.

`expires` set to `null` I think is okay, there is function which sets the `expires` on all messages using the settings in the configuration file. It will only amend the `null` values so that any manually set expiry times are kept.

I will leave this issue open for a bit if anyone else has any comments.

Working on a version 1.2.0 at the moment.

**Comment by dels07** [comment]
It could be good if you also provide bootstrap + jquery solution as default (or as an option).

**Comment by clnt** [comment]
I could add that as an option, however I feel that may defeat the purpose of this package, the flash package by laracasts does exactly that but pulls the data directly via PHP. 

I could possibly add a jquery/bootstrap solution that can be enabled/disabled in config and uses the generated JS data, I will add it to a list and give it some thought.

This package is designed to be used alongside Vue, Angular, React or other JS Frameworks which is why it places the data in a JavaScript variable within your view.

This data can then be accessed and displayed however the developer wants. I will look at adding included JS components in a future release, but for now I think what I have included in the docs is fine.

I have just added a GIF preview of this package when used with [vue-toast](https://github.com/AStaroverov/vue-toast) to the README.md and Documentation.
