### ISSUE TITLE
laralabs/toaster 1.0.0 requires php >=7.0 -> your PHP version (5.6.15) does not satisfy that requirement.

### ISSUE THREAD

**Issue by anildsvv14** [Laralabs/toaster#4]
Hello i am using php version 5.6.15 and laravel 5.4 for my local project but when i update my composer  "laralabs/toaster": "~1.1.0" and run composer update it is showing me  error **laralabs/toaster 1.0.0 requires php >=7.0 -> your PHP version (5.6.15) does not satisfy that requirement.** so i want to know that does this package is not for php 5.6 but in documentation you are showing this http://docs.laralabs.uk/toaster/1.1.0/index.html

**Comment by clnt** [comment]
Hi mate,

Please use version 2.0.1 which only supports PHP 7.0 + 

I will delete the old documentation, as I have also deleted those tags due to issues on them, I thought they had also been removed from Packagist so my bad.

http://docs.laralabs.uk/toaster/

Planning to update this package in the next couple of weeks to support L5.6

**Comment by anildsvv14** [comment]
Thanks for your quick response i will wait for your next update
